<?php
function swx_geospace_init() {
  // this string is a superset of the other, so test for it first
  if (strpos(request_uri(), 'geospace-geomagnetic-dynamic-activity-plot') !== false) {
    $modulePath = drupal_get_path('module', 'swx_geospace');

    drupal_add_js($modulePath . '/chart.js', 'file');
    drupal_add_css($modulePath . '/chart.css');

    $highchart_path = libraries_get_path('highcharts');
    
    drupal_add_js($highchart_path . '/highstock.js' , 'file');
    //drupal_add_js($highchart_path . '/exporting.js' , 'file');
  }
}
